version: '3.8'

services:
  postgres:
    container_name: freight-shipping-db
    image: postgres:17 # Specifies PostgreSQL version 17
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypwd
      # Development-friendly settings
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      # Enable detailed logging for development
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 0
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Mount init scripts for development
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
    # Local development resource limits (used by docker-compose)
    mem_limit: 512m     # Memory limit for local development
    cpus: 0.5          # CPU limit for local development
    restart: unless-stopped # Better for local development than 'always'
    # Development-friendly health check
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d myapp"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: